Update main.yml
添加linuxdeployqt 的 -unsupported-allow-new-glibc 以解决 
ERROR: The host system is too new.
Please run on a system with a glibc version no newer than what comes with the oldest
currently supported mainstream distribution (Ubuntu Jammy Jellyfish), which is glibc 2.35.
This is so that the resulting bundle will work on most still-supported Linux distributions.
For more information, please see
https://github.com/probonopd/linuxdeployqt/issues/340
报错